name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'app-container/**'

defaults:
  run:
    working-directory: app-container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/app-container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS.ACCES_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS.SECRET_ACCESS_KEY }}
